### ISSUE TITLE
Inline between text

### ISSUE THREAD

**Issue by souzadavi** [mmirus/monarch-sharing-shortcode#2]
Hello nice code. I would like to added the shortcode on middle of the post text. But this code add the share button on top or footer... Do you know if is it possible to add it in middle of post?

thanks in advance!

**Comment by souzadavi** [comment]
I changed the line 42 to:

`<div class="et_social_inline%10$s %12$s %14$s">`

than did the magic!

**Comment by mmirus** [comment]
Glad you got something figured out!
